version: '3.9'

services:
  app:
    image: python:3.8-slim
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "sudo pip install psycopg2 && python main.py "

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=db

  jupyter:
    image: jupyter/datascience-notebook
    volumes:
      - ./:/home/jovyan
    ports:
      - "8888:8888"
    environment:
      - POSTGRES_HOST=postgres